$terminal = foot
$browser = google-chrome-stable
$editor = codium
$fileExplorer = dolphin

$windowGapsIn = 3
$windowGapsOut = 5
$singleWindowGapsOut = 5

$windowOpacity = 0.95

$shadowEnabled = false

# Restart hyprsunset
bind = Super, BackSpace, exec, sh -c 'pkill hyprsunset && notify-send "Killed hyprsunset" || notify-send "Failed to kill hyprsunset"; sleep 2; notify-send "Starting hyprsunset..."; hyprsunset'

bindn = Super, equal, exec, hyprctl hyprsunset temperature +250
bindn = Super, minus, exec, hyprctl hyprsunset temperature -250
bindn = Super, backslash, exec, hyprctl hyprsunset temperature 6000  # Reset to default

# Pass input to discord hack
bindl = , Caps_Lock, pass, class:^(discord)$

dwindle {
  force_split = 2
}

input {
  accel_profile = flat
}

misc {
  vrr = 0
}

# Figure out how to open these in workspaces
# exec-once = google-chrome-stable
# exec-once = discord
# exec-once = spotify
# exec-once = steam
exec-once = hyprsunset

env = EDITOR, nvim
