$terminal = foot
$browser = google-chrome-stable
$editor = codium
$fileExplorer = dolphin

$windowGapsIn = 3
$windowGapsOut = 10
$singleWindowGapsOut = 10

# Restart hyprsunset
bind = Super, BackSpace, exec, pkill hyprsunset && notify-send "Killed hyprsunset"; sleep 1; (hyprsunset && notify-send "Restarted hyprsunset") || notify-send "Failed to start hyprsunset"

bind = Super, equal, exec, hyprctl hyprsunset temperature +200 
bind = Super, minus, exec, hyprctl hyprsunset temperature -200 

# Pass input to discord hack
bindl = , Caps_Lock, pass, class:^(discord)$

dwindle {
  force_split = 2
}

input {
  accel_profile = flat
}

# Figure out how to open these in workspaces
# exec-once = google-chrome-stable
# exec-once = discord
# exec-once = spotify
# exec-once = steam
exec-once = hyprsunset
